/* extra pages: info pages, 404, templates, account */
const INFO={
about:['About FARVO Prompt','<p>FARVO Prompt turns a rough idea into a clear, structured prompt you can paste into ChatGPT, Gemini or Claude. Write in English, Tamil, Sinhala, Hindi or Tanglish.</p><h3>What you can do</h3><ul><li>Generate prompts for study, coding, design, business, writing and more</li><li>Turn an image into an image-generation prompt</li><li>Check and improve prompts you already have</li><li>Start from ready-made templates and save results in your library</li></ul><p>Built by <b>FARVO Digital Company</b>.</p>'],
faq:['Frequently asked questions','<details><summary>Is this a live AI?</summary><p>No. Prompts are built by a rule-based engine in your browser. You paste the result into the AI tool you prefer.</p></details><details><summary>Where is my data stored?</summary><p>Accounts, saved prompts and settings stay in this browser on this device. Nothing is sent to a server.</p></details><details><summary>I changed device and my account is gone.</summary><p>Accounts are per browser. Use Account, Export my data, before switching, or ask us about a cloud version.</p></details><details><summary>I forgot my password.</summary><p>Use Forgot password on the log in page and confirm your email and phone number.</p></details><details><summary>Is my uploaded image sent anywhere?</summary><p>No. It is analysed inside your browser only.</p></details>'],
privacy:['Privacy policy','<p>Your account, saved prompts and history stay in your own browser storage and are not sent to a server. Two features do use a server: messages sent through the Contact form are emailed to FARVO, and reviews you post are stored and shown publicly with the name and comment you enter. Do not put private details in a review.</p><h3>What is stored</h3><p>In your browser: name, phone, email, a hashed password, saved prompts, history and theme. On our servers: contact messages (emailed to us) and public reviews (name, rating, comment).</p><h3>Your control</h3><p>You can export or delete all of it from the Account page, or by clearing this site\'s data in your browser.</p><h3>Third parties</h3><p>Google Fonts is loaded for the typeface. The site is hosted on Vercel, contact emails are delivered through Resend and reviews are stored in Upstash Redis. Prompts you copy and paste into other AI tools are covered by those tools\' own policies.</p><p class="mut">This is a general notice, not legal advice. Review it before commercial use.</p>'],
terms:['Terms of use','<p>FARVO Prompt is provided as is, without warranty. Generated prompts are suggestions: check the AI output you get from them before relying on it.</p><ul><li>Do not use the tool for unlawful or harmful content.</li><li>Reviews must be honest and free of abuse or personal data. FARVO may remove any review.</li><li>You are responsible for keeping your device and password safe.</li><li>Data lives in your browser and can be lost if you clear it. Export regularly.</li></ul><p class="mut">This is a general notice, not legal advice. Review it before commercial use.</p>']};
function infoPage(t,body){$('#root').innerHTML=`<div class="top"><a href="#/" style="text-decoration:none;color:inherit">${logo}</a><span class="sp"></span><button class="ic" id="th" aria-label="Toggle theme">${root.dataset.theme==='dark'?'☀':'☾'}</button></div><main class="doc"><h1>${t}</h1>${body}<p><a class="btn sm" href="#/">Back to FARVO Prompt</a></p></main>${footer()}`;$('#th').onclick=toggleTheme;document.title=t+' - FARVO Prompt';scrollTo(0,0)}
function route(){const k=location.hash.replace(/^#\/?/,'');document.title='FARVO Prompt - AI prompt builder';
 if(k==='contact')return contactPage();if(k==='reviews')return reviewsPage();if(INFO[k])return infoPage(INFO[k][0],INFO[k][1]);
 if(k)return infoPage('Page not found','<p>This page does not exist. Check the link or go back to the app.</p>');
 boot()}
/* templates */
const TPLS=[['Exam notes','Study','I need exam notes for [TOPIC] with examples and 5 practice questions'],['MCQ quiz','Study','Create 20 multiple choice questions on [TOPIC] with answers and explanations'],['Presentation outline','Work','Create a 10 slide presentation on [TOPIC] for [AUDIENCE]'],['PHP + MySQL system','Coding','Build a [SYSTEM NAME] with PHP and MySQL including database design, login and admin panel'],['Debug my code','Coding','Debug this code and explain the fix step by step: [PASTE CODE]'],['Project poster','Design','Modern poster for my [PROJECT] with purple and black colours'],['Instagram caption','Social','Write 3 Instagram captions with hashtags for [PRODUCT OR EVENT]'],['Internship email','Career','Professional email asking for an internship at [COMPANY]'],['Resume summary','Career','Write a resume summary for a [ROLE] fresher with skills in [SKILLS]'],['Business proposal','Business','Write a business proposal for [SERVICE] for a client in [INDUSTRY]'],['Product description','Business','Write a product description for [PRODUCT] that highlights benefits'],['Weekly study plan','Productivity','Create a weekly schedule to study [SUBJECTS] in [HOURS] hours per day']];
function tplView(){$('#view').innerHTML=`<h2 style="margin-top:0">Templates</h2><p class="mut">Pick a starting point. Replace the [BRACKETS] with your details.</p><div class="tg">${TPLS.map((t,i)=>`<div class="lib"><b>${esc(t[0])}</b><span class="mut" style="font-size:12px">${esc(t[1])}</span><p>${esc(t[2])}</p><button class="btn sm" data-u="${i}">Use template</button></div>`).join('')}</div>`;
 document.querySelectorAll('[data-u]').forEach(b=>b.onclick=()=>{S.set('fp_tpl',TPLS[b.dataset.u][2]);curs.gen=null;cur=null;tab='gen';showApp();scrollTo(0,0)})}
/* account */
function accView(){const u=me();$('#view').innerHTML=`<div class="grid"><div class="card"><h2 style="margin-top:0">Your account</h2><p class="mut">${esc(u.email)}</p>${fld('an','Full name','text','','name')}${fld('ap','Phone number','tel','','tel')}<button class="btn full" id="sp">Save changes</button>
 <h3>Change password</h3>${fld('op','Current password','password','','current-password')}${fld('np','New password','password','Min 8 characters, letters and numbers','new-password')}${fld('np2','Confirm new password','password','','new-password')}<button class="btn full" id="cpw">Change password</button></div>
 <div class="card"><h2 style="margin-top:0">Your data</h2><p class="mut">Everything is stored in this browser only.</p><div class="row"><button class="btn sm" id="ex">Export my data</button><button class="btn sm ghost" id="cl">Clear library</button><button class="btn sm ghost" id="dl">Delete account</button></div></div></div>`;
 $('#an').value=u.name;$('#ap').value=u.phone;
 const save=us=>S.set('fp_users',us),dg=s=>s.replace(/\D/g,'');
 $('#sp').onclick=()=>{document.querySelectorAll('.err').forEach(e=>e.textContent='');let n=0;if(v('an').length<2)n+=bad('an','Enter your full name.');const d=dg(v('ap'));if(d.length<9||d.length>15)n+=bad('ap','Enter a valid phone number.');if(n)return;const us=S.get('fp_users',[]),x=us.find(a=>a.email===u.email);x.name=v('an');x.phone=d;save(us);toast('Changes saved')};
 $('#cpw').onclick=async()=>{document.querySelectorAll('.err').forEach(e=>e.textContent='');let n=0;const np=v('np');if(await hs(v('op'))!==u.pw)n+=bad('op','Current password is incorrect.');if(!(np.length>=8&&/[A-Za-z]/.test(np)&&/\d/.test(np)))n+=bad('np','Use 8+ characters with letters and numbers.');if(v('np2')!==np)n+=bad('np2','Passwords do not match.');if(n)return;const us=S.get('fp_users',[]);us.find(a=>a.email===u.email).pw=await hs(np);save(us);toast('Password changed');accView()};
 $('#ex').onclick=()=>{const o={name:u.name,phone:u.phone,email:u.email,library:S.get(libKey(),[])},a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(o,null,2)],{type:'application/json'}));a.download='farvo-prompt-data.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)};
 $('#cl').onclick=()=>{if(confirm('Delete all saved prompts?')){S.set(libKey(),[]);toast('Library cleared')}};
 $('#dl').onclick=()=>{if(!confirm('Delete your account and all saved prompts? This cannot be undone.'))return;try{localStorage.removeItem(libKey());localStorage.removeItem(histKey())}catch(e){}S.set('fp_users',S.get('fp_users',[]).filter(a=>a.email!==u.email));S.set('fp_session','');mode='login';cur=null;showAuth()}}

/* ---------- library: search, edit, history ---------- */
let LV='saved',LQ='',LE=null;
const histKey=()=>'fp_hist_'+S.get('fp_session');
function logHist(){const h=S.get(histKey(),[]),text=flat(cur.sections);if(h[0]&&h[0].text===text)return;h.unshift({id:Date.now(),title:String(cur.src||cur.c).slice(0,60),text,c:cur.c});S.set(histKey(),h.slice(0,50))}
function libView(){
 $('#view').innerHTML=`<h2 style="margin-top:0">Prompt Library</h2><div class="tabs">${[['saved','Saved'],['hist','History']].map(x=>`<button class="chip ${LV===x[0]?'on':''}" data-v="${x[0]}">${x[1]}</button>`).join('')}</div><input id="lq" type="search" placeholder="Search prompts…" aria-label="Search prompts" value="${esc(LQ)}">${LV==='saved'?`<div class="tabs">${['All','★',...FOLDERS].map(f=>`<button class="chip ${fold===f?'on':''}" data-f="${f}">${f==='★'?'★ Favorites':f}</button>`).join('')}</div>`:''}<div id="ll" style="margin-top:14px"></div>`;
 document.querySelectorAll('[data-v]').forEach(b=>b.onclick=()=>{LV=b.dataset.v;LE=null;libView()});
 document.querySelectorAll('[data-f]').forEach(b=>b.onclick=()=>{fold=b.dataset.f;libView()});
 $('#lq').oninput=e=>{LQ=e.target.value;drawLib()};
 $('#ll').onclick=e=>{const b=e.target.closest('[data-a]');if(!b)return;const a=b.dataset.a,key=LV==='saved'?libKey():histKey(),l=S.get(key,[]),x=l.find(i=>String(i.id)===b.dataset.id);
  if(a==='cp'&&x)copy(x.text);
  else if(a==='fav'&&x){x.fav=!x.fav;S.set(key,l);drawLib()}
  else if(a==='del'){S.set(key,l.filter(i=>String(i.id)!==b.dataset.id));drawLib()}
  else if(a==='ed'&&x){LE=x.id;drawLib()}
  else if(a==='no'){LE=null;drawLib()}
  else if(a==='ok'&&x){const tx=($('#ex2').value||'').trim();if(!tx)return toast('Prompt text cannot be empty');x.title=v('et')||x.title;x.text=tx;S.set(key,l);LE=null;toast('Prompt updated');drawLib()}
  else if(a==='sv'&&x){const s=S.get(libKey(),[]);s.unshift({id:Date.now(),text:x.text,title:x.title,folder:'Personal',fav:false});S.set(libKey(),s);toast('Saved to Personal')}
  else if(a==='clr'&&confirm('Clear all history?')){S.set(histKey(),[]);drawLib()}};
 drawLib()}
function drawLib(){const h=LV==='hist',l=S.get(h?histKey():libKey(),[]),q=LQ.toLowerCase(),
 shown=l.filter(x=>(h||(fold==='All'?1:fold==='★'?x.fav:x.folder===fold))&&(!q||(x.title+' '+x.text).toLowerCase().includes(q)));
 const item=x=>x.id===LE?`<div class="lib"><label for="et" style="margin-top:0">Title</label><input id="et" value="${esc(x.title)}"><label for="ex2">Prompt</label><textarea id="ex2" style="min-height:180px">${esc(x.text)}</textarea><div class="row"><button class="btn sm" data-a="ok" data-id="${x.id}">Save changes</button><button class="btn sm ghost" data-a="no">Cancel</button></div></div>`
 :`<div class="lib"><b>${esc(x.title)}</b> <span class="mut" style="font-size:12px">· ${esc(h?x.c:x.folder)}</span><pre>${esc(x.text)}</pre><div class="row" style="margin-top:0"><button class="btn sm" data-a="cp" data-id="${x.id}">Copy</button>${h?`<button class="btn sm ghost" data-a="sv" data-id="${x.id}">Save</button>`:`<button class="btn sm ghost" data-a="fav" data-id="${x.id}">${x.fav?'★ Favorite':'☆ Favorite'}</button><button class="btn sm ghost" data-a="ed" data-id="${x.id}">Edit</button>`}<button class="btn sm ghost" data-a="del" data-id="${x.id}">Delete</button></div></div>`;
 $('#ll').innerHTML=(h&&l.length?'<div class="row" style="margin:0 0 12px"><button class="btn sm ghost" data-a="clr">Clear history</button></div>':'')+(shown.length?shown.map(item).join(''):`<div class="card"><b>${q?'No matches.':h?'No history yet.':'Nothing here yet.'}</b><p class="mut">${q?'Try a different word.':h?'Prompts you generate appear here automatically (last 50).':'Generate a prompt and press Save to keep it here.'}</p></div>`)}
/* ---------- contact + reviews (need /api on Vercel) ---------- */
async function post(u,d){const r=await fetch(u,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(d)});let j={};try{j=await r.json()}catch(e){}if(!r.ok)throw new Error(j.error||'Something went wrong. Please try again.');return j}
const clr=()=>document.querySelectorAll('.err').forEach(e=>e.textContent='');
const mailRx=/^[^\s@]+@[^\s@]+\.[^\s@]{2,}$/,stars=n=>'★'.repeat(n)+'☆'.repeat(5-n);
function contactPage(){const u=me()||{};
 infoPage('Contact us',`<p>Questions, bugs or a custom website or app? Send a message and we will reply by email.</p><form id="cf" novalidate class="card">${fld('cn','Name','text','Your name','name')}${fld('ce','Email','email','you@example.com','email')}<label for="cm">Message</label><textarea id="cm" maxlength="2000" placeholder="How can we help?"></textarea><span class="err" id="e_cm"></span><input id="cw" tabindex="-1" autocomplete="off" aria-hidden="true" style="position:absolute;left:-9999px;width:1px"><button class="btn full" id="cs" type="submit" style="margin-top:14px">Send message</button><span id="cr" role="status" class="ok"></span></form><p class="mut">Or call <a href="tel:+94773042864">+94 077 304 2864</a> · <a href="https://wa.me/94773042864" target="_blank" rel="noopener">WhatsApp</a> · <a href="https://farvodigital.netlify.app" target="_blank" rel="noopener">farvodigital.netlify.app</a></p>`);
 $('#cn').value=u.name||'';$('#ce').value=u.email||'';
 $('#cf').onsubmit=async e=>{e.preventDefault();clr();$('#cr').textContent='';let n=0;if(v('cn').length<2)n+=bad('cn','Enter your name.');if(!mailRx.test(v('ce')))n+=bad('ce','Enter a valid email address.');if(v('cm').length<5)n+=bad('cm','Write a short message.');if(n)return;
  const b=$('#cs');b.disabled=true;b.textContent='Sending…';
  try{await post('/api/contact',{name:v('cn'),email:v('ce'),message:v('cm'),website:$('#cw').value});$('#cm').value='';$('#cr').textContent='Message sent. We will reply to your email soon.'}
  catch(x){bad('cm',x.message+' You can also call or WhatsApp us.')}
  b.disabled=false;b.textContent='Send message'}}
function reviewsPage(){
 infoPage('Reviews',`<div id="rsum" class="mut">Loading…</div><form id="rf" novalidate class="card" style="margin:16px 0">${fld('rn','Your name','text','Your name','name')}<label for="rr">Rating</label><select id="rr">${[5,4,3,2,1].map(n=>`<option value="${n}">${stars(n)} (${n})</option>`).join('')}</select><label for="rc">Your review</label><textarea id="rc" maxlength="500" placeholder="What did you like? What can be better?"></textarea><span class="err" id="e_rc"></span><input id="rw" tabindex="-1" autocomplete="off" aria-hidden="true" style="position:absolute;left:-9999px;width:1px"><button class="btn full" id="rs" type="submit" style="margin-top:14px">Post review</button></form><div id="rl"></div>`);
 $('#rn').value=(me()||{}).name||'';
 $('#rf').onsubmit=async e=>{e.preventDefault();clr();let n=0;if(v('rn').length<2)n+=bad('rn','Enter your name.');if(v('rc').length<5)n+=bad('rc','Write at least a few words.');if(n)return;
  const b=$('#rs');b.disabled=true;b.textContent='Posting…';
  try{await post('/api/reviews',{name:v('rn'),rating:+$('#rr').value,comment:v('rc'),website:$('#rw').value});$('#rc').value='';toast('Thanks for your review!');await loadReviews()}catch(x){bad('rc',x.message)}
  b.disabled=false;b.textContent='Post review'};
 loadReviews()}
async function loadReviews(){const box=$('#rl'),sum=$('#rsum');if(!box)return;
 try{const r=await fetch('/api/reviews');if(!r.ok)throw 0;const j=await r.json();
  sum.innerHTML=j.count?`<b style="font-size:24px">${j.avg}</b> <span style="color:#f59e0b">${stars(Math.round(j.avg))}</span> <span class="mut">${j.count} review${j.count>1?'s':''}</span>`:'No reviews yet. Be the first!';
  box.innerHTML=j.reviews.map(x=>`<div class="lib"><b>${esc(x.n)}</b> <span style="color:#f59e0b" role="img" aria-label="${x.r} out of 5 stars">${stars(x.r)}</span> <span class="mut" style="font-size:12px">${new Date(x.t).toLocaleDateString()}</span><p style="margin:6px 0 0;white-space:pre-wrap">${esc(x.c)}</p></div>`).join('')}
 catch(e){sum.textContent='Reviews cannot load right now. They work on the deployed site.';box.innerHTML=''}}
